Improve de-DE (German) Translation
nutdotnet/WinNUT-Client pull request #8
Opened 2022-07-25 22:24 UTC by gbakeman

Update the German translation. Primary pull request is based on Lineflyer's https://github.com/gawindx/WinNUT-Client/pull/108.

Related PRs: https://github.com/gawindx/WinNUT-Client/pull/80, https://github.com/gawindx/WinNUT-Client/pull/131

2022-07-26 09:48 UTC, MarkusMDK requested changes
Very good translation. I only have a few small suggestions for changes.

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Nut server address. Accepted value: IPV4 / IPV6 / FQDN address.,Nut-Serveradresse. Wertebereich: IPV4 / IPV6 / FQDN-Adresse.
```suggestion
Valid,Lineflyer,Nut server address. Accepted value: IPV4 / IPV6 / FQDN address.,NUT-Serveradresse. Wertebereich: IPV4 / IPV6 / FQDN-Adresse.
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Login credentials to the Nut server (leave blank if not required),Anmeldeinformationen des Nut-Server (Leer lassen wenn nicht erforderlich)
```suggestion
Valid,Lineflyer,Login credentials to the Nut server (leave blank if not required),Anmeldeinformationen des NUT-Server (Leer lassen wenn nicht erforderlich)
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Disconnected from Nut Host,Vom Nut-Host getrennt
```suggestion
Valid,Lineflyer,Disconnected from Nut Host,Vom NUT-Host getrennt
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +To validate,Lineflyer,On Battery ({0}%),Auf Batterie ({0}%)
```suggestion
To validate,Lineflyer,On Battery ({0}%),Im Batteriebetrieb ({0}%)
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +To validate,Lineflyer,On Line,Auf Netzbetrieb
```suggestion
To validate,Lineflyer,On Line,Im Netzbetrieb
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Starts WinNut Minimized.,Startet WinNut minimiert.
```suggestion
Valid,Lineflyer,Starts WinNut Minimized.,Startet WinNUT minimiert.
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Update WinNUT-Client Now? Ok to Close WinNut and Install New Version Cancel to Save Msi and Install Later,WinNUT-Client jetzt aktualisieren? OK um WinNut zu schließen und neue Version
```suggestion
Valid,Lineflyer,Update WinNUT-Client Now? Ok to Close WinNut and Install New Version Cancel to Save Msi and Install Later,WinNUT-Client jetzt aktualisieren? OK um WinNUT zu schließen und neue Version zu installieren Abbrechen um MSI-Datei zu speichern und später zu installieren
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,UPS name to monitor. Accepted Value: Name of the UPS configured in the Nut server.,Name der zu überwachenden USV. Wertebereich: Name der auf dem Nut-Server konfigurierten USV.
```suggestion
Valid,Lineflyer,UPS name to monitor. Accepted Value: Name of the UPS configured in the Nut server.,Name der zu überwachenden USV. Wertebereich: Name der auf dem NUT-Server konfigurierten USV.
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Gawindx,WinNut Preferences Changed,WinNut-Einstellungen geändert
```suggestion
Valid,Gawindx,WinNut Preferences Changed,WinNUT-Einstellungen geändert
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Gawindx,Connection to Nut Host {0}:{1} Established,Verbindung zum Nut Host {0}:{1} hergestellt
```suggestion
Valid,Gawindx,Connection to Nut Host {0}:{1} Established,Verbindung zum NUT-Host {0}:{1} hergestellt
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Gawindx,Connection to Nut Host {0}:{1} Failed: {2},Verbindung zum Nut-Host {0}:{1} fehlgeschlagen: {2}
```suggestion
Valid,Gawindx,Connection to Nut Host {0}:{1} Failed: {2},Verbindung zum NUT-Host {0}:{1} fehlgeschlagen: {2}
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Nut Server Port Number (default = 3493). Accepted value: Numeric value from 1 to 65535.,Nut-Server Portnummer (Standard = 3493). Wertebereich: Numerischer Wert von 1 bis 65535.
```suggestion
Valid,Lineflyer,Nut Server Port Number (default = 3493). Accepted value: Numeric value from 1 to 65535.,NUT-Server Portnummer (Standard = 3493). Wertebereich: Numerischer Wert von 1 bis 65535.
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Gawindx,UPS On Battery,USV im Akkubetrieb
```suggestion
Valid,Gawindx,UPS On Battery,USV im Batteriebetrieb
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Close to Systray,Auf Systray minimieren
```suggestion
Valid,Lineflyer,Close to Systray,In Systray minimieren
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Gawindx,Minimize to Systray,Auf Systray minimieren
```suggestion
Valid,Gawindx,Minimize to Systray,In Systray minimieren
```

2022-07-26 09:48 UTC, MarkusMDK commented on Translation/de-DE/de-DE.csv
> +Valid,Lineflyer,Reduced to the taskbar or Systray.,Auf Taskleiste oder Systray minimieren.
```suggestion
Valid,Lineflyer,Reduced to the taskbar or Systray.,In Taskleiste oder Systray minimieren.
```

2022-07-27 23:03 UTC, gbakeman commented
Great work, thank you @MarkusMDK.

2022-07-27 23:04 UTC, merged